I will initialize 3 large random tensors, and then do the operations as given in the computational graph below: 

![Image of a computational graph](images/comp_graph.png)

The final operation is the mean of the tensor, given by torch.mean(your_tensor).

In [6]:
import torch

# Initialize tensors x, y and z
x = torch.tensor(torch.rand(1000, 1000), requires_grad=True)
y = torch.tensor(torch.rand(1000, 1000), requires_grad=True)
z = torch.tensor(torch.rand(1000, 1000), requires_grad=True)

/var/folders/j0/65tsv5t54nqf1fn684hcdmt80000gn/T/ipykernel_98833/3609918814.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(torch.rand(1000, 1000), requires_grad=True)
/var/folders/j0/65tsv5t54nqf1fn684hcdmt80000gn/T/ipykernel_98833/3609918814.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(torch.rand(1000, 1000), requires_grad=True)
/var/folders/j0/65tsv5t54nqf1fn684hcdmt80000gn/T/ipykernel_98833/3609918814.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.tensor(torch.rand(1000, 1000

I now calculate the gradients.

In [7]:
# Multiply tensors x and y
q = torch.matmul(x, y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

# Calculate the gradients
print(mean_f.backward())

print(x.grad)
print(y.grad)
print(z.grad)

tensor(124.7904, grad_fn=<MeanBackward0>)
None
tensor([[0.0002, 0.0002, 0.0003,  ..., 0.0002, 0.0002, 0.0002],
        [0.0003, 0.0003, 0.0003,  ..., 0.0003, 0.0002, 0.0003],
        [0.0003, 0.0003, 0.0003,  ..., 0.0002, 0.0002, 0.0002],
        ...,
        [0.0003, 0.0003, 0.0003,  ..., 0.0002, 0.0003, 0.0003],
        [0.0003, 0.0003, 0.0003,  ..., 0.0002, 0.0002, 0.0002],
        [0.0003, 0.0003, 0.0003,  ..., 0.0003, 0.0003, 0.0003]])
tensor([[0.0003, 0.0003, 0.0002,  ..., 0.0002, 0.0003, 0.0003],
        [0.0003, 0.0002, 0.0002,  ..., 0.0002, 0.0003, 0.0002],
        [0.0003, 0.0003, 0.0002,  ..., 0.0002, 0.0003, 0.0002],
        ...,
        [0.0003, 0.0003, 0.0002,  ..., 0.0002, 0.0003, 0.0002],
        [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
        [0.0003, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002]])
tensor([[0.0003, 0.0002, 0.0002,  ..., 0.0002, 0.0003, 0.0002],
        [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
        [0.0003, 0.0002, 0.00